name: Generate Contribution Terrain

on:
  workflow_dispatch: # manual run
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }} # use your PAT for push access

      - name: Create output directory
        run: mkdir -p images

      - name: Generate Contribution Terrain
        uses: eshahhh/contribution-terrain@v1.0.0
        with:
          username: ${{ github.repository_owner }}
          style: terrain
          output_dir: images
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update contribution terrain"
            git push
          fi
